Repository GoogleCloudPlatform/testgrid, pull requests merged in 2019-09, with the labels that each got.

#6 Fix update-bazel test
  BUILD.bazel
  hack/update-bazel.sh
Labels: approved, lgtm

#8 Change Build Cluster Settings
  .bazelrc
  cluster/BUILD.bazel
  cluster/entomologist_deployment.yaml
  cluster/setup.sh
  hack/print-workspace-status.sh
Labels: approved, lgtm, size/L

#10 Fixing go.mod module path.
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#11 Modify Image Creation
  cmd/configurator/BUILD.bazel
  cmd/entomologist/BUILD.bazel
  cmd/summarizer/BUILD.bazel
  cmd/updater/BUILD.bazel
  config-upload.sh
Labels: approved, lgtm, size/M

#12 Updating go.mod to use 1.13, patching deps.
  go.mod
  go.sum
  repos.bzl
Labels: approved, lgtm, size/M

#16 Remove "Configurator" from TestGrid Repository
  BUILD.bazel
  build_test_update.md
  cluster/BUILD.bazel
  cluster/configurator_deployment.yaml
  cmd/configurator/BUILD.bazel
  cmd/configurator/README.md
  cmd/configurator/main.go
  cmd/configurator/main_test.go
  cmd/configurator/prow.go
  cmd/configurator/prow_test.go
  cmd/configurator/yaml2proto.go
  cmd/configurator/yaml2proto_test.go
  config.md
  go.mod
  images/BUILD.bazel
Labels: approved, lgtm, size/XXL

#14 Add push script for TestGrid
  images/push.sh
Labels: approved, lgtm, size/M

#20 Removing conformance files, they're Kubernetes-specific.
  conformance/README.md
  conformance/creating-a-bucket.md
  conformance/design.md
  conformance/upload_e2e.py
Labels: approved, lgtm, size/L
