Repository GoogleCloudPlatform/testgrid, pull requests merged in 2019-11, with the labels that each got.

#46 Update config proto with ignore_skip option.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#47 Delete RPC-based summarizer
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/example/BUILD.bazel
  cmd/summarizer/example/client.go
  cmd/summarizer/example/fake_response.go
  cmd/summarizer/server.go
  cmd/summarizer/summarizer.go
  cmd/summarizer/summarizer_test.go
  cmd/summarizer/summary/BUILD.bazel
  cmd/summarizer/summary/summarizer_service.pb.go
  cmd/summarizer/summary/summarizer_service.proto
  go.mod
  go.sum
  repos.bzl
Labels: approved, lgtm, size/XL

#48 Create state based summarizer
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/summarizer/main_test.go
  cmd/updater/main.go
  go.mod
  go.sum
  pb/state/state.pb.go
  pb/state/state.proto
  repos.bzl
Labels: approved, lgtm, size/XL

#49 TestUpdateDashboard TestUpdateTab TestReadGrid
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/summarizer/main_test.go
Labels: approved, lgtm, size/L

#50 Actually reconcile ignore_skip in default.yaml.
  config/yamlcfg/yaml2proto.go
Labels: approved, lgtm, size/XS

#52 Unit tests for all functionality
  cmd/summarizer/main.go
  cmd/summarizer/main_test.go
Labels: approved, lgtm, size/XXL

#54 Add fail_time and pass_time to AlertInfo.
  hack/BUILD.bazel
  hack/update-protos.sh
  hack/verify-protos.sh
  pb/state/BUILD.bazel
  pb/state/state.pb.go
  pb/state/state.proto
Labels: approved, lgtm, size/L

#53 Create summary status message
  cmd/summarizer/main.go
  cmd/summarizer/main_test.go
Labels: approved, lgtm, size/XXL

#56 Update the svg summary widget example with existing tab.
  README.md
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/S

#55 Make updater configure alerts.
  BUILD.bazel
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/summarizer/main_test.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  cmd/updater/main_test.go
  internal/result/BUILD.bazel
  internal/result/results.go
Labels: approved, lgtm, size/XL

#58 Allow reading from k8s-testgrid
  cluster/BUILD.bazel
  cluster/summarizer_deployment.yaml
  cluster/updater_deployment.yaml
  cmd/updater/main.go
  images/push.sh
Labels: approved, lgtm, size/S

#59 Allow reading from beta subdir
  cluster/summarizer_deployment.yaml
  cluster/updater_deployment.yaml
  cmd/summarizer/main.go
  cmd/updater/main.go
Labels: approved, lgtm, size/S

#60 Write summary to GCS
  cluster/summarizer_deployment.yaml
  cluster/updater_deployment.yaml
  cmd/summarizer/main.go
  cmd/updater/main.go
Labels: approved, lgtm, size/M

#61 Improve updater, summarizer, gcs reader
  cluster/summarizer_deployment.yaml
  cluster/updater_deployment.yaml
  cmd/summarizer/main.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  cmd/updater/main_test.go
  util/gcs/read.go
Labels: approved, lgtm, size/L

#65 Do not cache state, summary values.
  cluster/summarizer_deployment.yaml
  cluster/updater_deployment.yaml
  cmd/summarizer/main.go
  cmd/updater/main.go
  util/gcs/gcs.go
Labels: approved, lgtm, size/S

#66 Encapsulate how to get/set version in metadata package.
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  metadata/job.go
  metadata/job_test.go
Labels: approved, lgtm, size/L
