Repository GoogleCloudPlatform/testgrid, pull requests merged in 2019-10, with the labels that each got.

#21 Fixing imports in summarizer.
  cmd/summarizer/example/BUILD.bazel
  cmd/summarizer/example/client.go
  cmd/summarizer/example/fake_response.go
Labels: approved, lgtm, size/S

#23 Correctly map protos for .pb.go files.
  cmd/summarizer/summary/summarizer_service.pb.go
  hack/BUILD.bazel
  pb/response/types.pb.go
Labels: approved, lgtm, size/S

#24 Reuse k8s.io/repo-infra when possible
  .bazelrc
  .kazelcfg.json
  WORKSPACE
  def.bzl
  go.mod
  hack/.kazelcfg.json
  hack/BUILD.bazel
  hack/update-bazel.sh
  hack/update-deps.sh
  hack/update-gofmt.sh
  hack/verify-bazel.sh
  hack/verify-deps.sh
  hack/verify-gofmt.sh
  repos.bzl
Labels: approved, lgtm, size/XL

#25 Make oncall approvers
  OWNERS
Labels: approved, lgtm, size/S

#27 Updating the issue_state and test_status protos.
  pb/issue_state/issue_state.pb.go
  pb/issue_state/issue_state.proto
  pb/test_status/BUILD.bazel
  pb/test_status/test_status.pb.go
  pb/test_status/test_status.proto
Labels: approved, lgtm, size/L

#30 Remove direct dependencies to k8s/test-infra
  BUILD.bazel
  cluster/BUILD.bazel
  cluster/entomologist_deployment.yaml
  cmd/entomologist/BUILD.bazel
  cmd/entomologist/README.md
  cmd/entomologist/main.go
  cmd/entomologist/main_test.go
  def.bzl
  go.mod
  go.sum
  images/BUILD.bazel
  pb/BUILD.bazel
  pb/test_status/BUILD.bazel
  repos.bzl
Labels: approved, lgtm, size/XXL

#32 Remove "area/testgrid" label
  OWNERS
Labels: approved, lgtm, size/XS

#34 Refactoring of Config Libraries to include Yaml Config
  config/BUILD.bazel
  config/config.go
  config/config_test.go
  config/yamlcfg/BUILD.bazel
  config/yamlcfg/yaml2proto.go
  config/yamlcfg/yaml2proto_test.go
  go.mod
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/XXL

#37 Update to repo-infra v0.0.1-alpha.1
  WORKSPACE
  cmd/summarizer/summary/summarizer_service.pb.go
  go.mod
  go.sum
  hack/tools.go
  repos.bzl
  resultstore/client.go
Labels: approved, lgtm, size/L

#39 Switch to an http_archive for io_k8s_repo_infra
  WORKSPACE
Labels: approved, lgtm, size/S

#40 Fixup .bazelrc
  .bazelrc
Labels: approved, do-not-merge/hold, lgtm, size/M

#42 Also fixing .bazelrc
  .bazelrc
Labels: approved, lgtm, size/S

#44 Update bazel rules in Workspace
  WORKSPACE
Labels: approved, lgtm, size/S
