Repository GoogleCloudPlatform/testgrid, pull requests merged in 2019-12, with the labels that each got.

#67 Log progress every minute
  cmd/updater/main.go
Labels: approved, lgtm, size/M

#68 Read from correct metadata link
  cmd/updater/main.go
  util/gcs/read.go
Labels: approved, lgtm, size/XS

#69 Add/Rename Config.proto fields
  config/yamlcfg/yaml2proto.go
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#62 Simplify gcs and updater concurrency
  cluster/updater_deployment.yaml
  cmd/updater/main.go
  util/gcs/read.go
Labels: approved, lgtm, size/L

#70 Invert dashboard option for failing tabs
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#71 Write summary to summary-foo instead of dashboard-foo
  cmd/summarizer/main.go
Labels: approved, lgtm, size/XS

#72 Write summaries to gs://k8s-testgrid/summary-foo
  cluster/summarizer_deployment.yaml
Labels: approved, lgtm, size/XS

#75 Fix link for configuration docs.
  README.md
  build_test_update.md
Labels: approved, lgtm, size/XS
