Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-09, with the labels that each got.

#226 Add a column filter to flakiness algorithm
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
Labels: approved, lgtm, size/L

#227 Use test_status.proto.
  internal/result/BUILD.bazel
  internal/result/results.go
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  pkg/updater/BUILD.bazel
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XXL

#230 Update test status severity.
  internal/result/results.go
Labels: approved, lgtm, size/S

#229 Deduplicate alerting settings in proto
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/XL

#231 Switch seconds-elapsed to test-duration-minutes
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#232 Upgrade canary to v20200911-v0.0.21-2-gffa64bc
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#233 Promote v20200911-v0.0.21-2-gffa64bc to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#234 Migrate to new sortorder import path
  go.mod
  go.sum
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  repos.bzl
  util/gcs/BUILD.bazel
  util/gcs/read.go
Labels: approved, lgtm, ok-to-test, size/M

#235 If stale alerts not configured, don't alert on no runs.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/M

#237 Less updater concurrency by default
  cmd/updater/main.go
  cmd/updater/main_test.go
Labels: approved, lgtm, size/XS

#238 Add DashboardTabFlakinessAlertOptions to config.proto
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/XL

#240 Increase updater timeouts.
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#239 Alerter proto update
  pb/config/config.pb.go
  pb/config/config.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
Labels: approved, lgtm, size/XL
