Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-02, with the labels that each got.

#91 Refactor cmd/summarizer to import a pkg/summarizer library
  BUILD.bazel
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/XXL

#88 Use bazel 2.0.0 and repo-infra 0.0.1
  .bazelversion
  WORKSPACE
Labels: approved, lgtm, size/XS

#92 Use repo-infra v0.0.2
  .bazelversion
  WORKSPACE
  pb/config/BUILD.bazel
  pb/custom_evaluator/BUILD.bazel
  pb/issue_state/BUILD.bazel
  pb/response/BUILD.bazel
  pb/state/BUILD.bazel
  pb/summary/BUILD.bazel
  pb/test_status/BUILD.bazel
  pb/updater/BUILD.bazel
Labels: approved, lgtm, size/S

#94 Fix some lint errors
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#97 Refactor cmd/updater to import a pkg/updater library
  BUILD.bazel
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  pkg/summarizer/summary_test.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XXL

#95 Validate TestGrid config uses unique names.
  config/BUILD.bazel
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, lgtm, size/L

#99 Validate referenced entities exist in config.
  config/config.go
  config/config_test.go
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/L

#100 Create canary testgrid deployment.
  BUILD.bazel
  cluster/canary/BUILD.bazel
  cluster/canary/namespace.yaml
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
  cluster/deploy.sh
  cluster/prod/BUILD.bazel
  cluster/prod/namespace.yaml
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
  cluster/summarizer_serviceaccount.yaml
  cluster/updater_serviceaccount.yaml
Labels: approved, lgtm, size/L

#101 Support summarizing non kubernetes clients.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/M

#102 Handle scenario where grid is not found
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/M
