Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-07, with the labels that each got.

#141 Update testgrid's bazel and cloud.google.com/go dependencies
  .bazelversion
  WORKSPACE
  config/BUILD.bazel
  go.mod
  go.sum
  pb/updater/updater.pb.go
  pkg/summarizer/BUILD.bazel
  pkg/updater/BUILD.bazel
  repos.bzl
  util/gcs/BUILD.bazel
Labels: approved, lgtm, size/XL

#140 How to add multiple jobs in 1 test group.
  config.md
Labels: approved, lgtm, size/XS

#142 Change channel usage logic to drain channels
  pkg/summarizer/flakiness.go
Labels: approved, lgtm, ok-to-test, size/M

#144 Add a --grid-prefix flag.
  cmd/updater/main.go
  pkg/updater/updater.go
Labels: approved, lgtm, size/M

#145 Add missing gridPrefix option
  cmd/updater/main.go
Labels: approved, lgtm, size/XS

#146 Update canary testgrid to v20200714-v0.0.13-4-g708c3dd
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#143 Integrate Healthiness into Summarizer
  pb/config/config.pb.go
  pb/config/config.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/XXL

#148 Create namespace before objects in that namespace
  cluster/canary/BUILD.bazel
  cluster/prod/BUILD.bazel
Labels: approved, lgtm, size/XS

#149 Write to canary bucket
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#150 Update prod updater to 20200714, turn off confirm.
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#151 Use different service account for canary
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#152 Correct config location
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#154 Rollout v20200714 summarizer and updater to prod.
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#155 Flags to configure where summarizer reads/writes.
  cmd/summarizer/main.go
  pkg/summarizer/summary.go
Labels: approved, lgtm, size/M

#153 Update to golang 1.14 (via repo infra 0.0.7), logrus 1.6, and improve…
  WORKSPACE
  cmd/updater/main.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, lgtm, size/M

#156 Change Healthiness report to filter out test methods
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
Labels: approved, lgtm, size/M

#157 Prevent writing grid state to gs://k8s-testgrid, allow a subdir
  cmd/updater/main.go
Labels: approved, lgtm, size/XS

#160 Restore some state proto documentation
  pb/state/state.pb.go
  pb/state/state.proto
Labels: approved, lgtm, size/M

#162 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#163 Add more state proto Result fields and better pass/fail categorization
  internal/result/results.go
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
Labels: approved, lgtm, size/L

#161 Functions to reinflate compressed grid messages.
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/updater/BUILD.bazel
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
Labels: approved, lgtm, size/XL

#165 Upgrade canary testgrid to v20200723-v0.0.14-26-gd07545a
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#166 Refactor how we read test suites.
  util/gcs/BUILD.bazel
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#167 Add LinkedBugs in the summary.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/S

#164 Convert a GCS result into an inflatedColumn.
  pkg/updater/BUILD.bazel
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/updater.go
Labels: approved, lgtm, size/XL

#168 Suites() coverage
  pkg/updater/updater.go
  util/gcs/BUILD.bazel
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/XL

#169 Test coverage for Started() and Finished()
  util/gcs/BUILD.bazel
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#170 Rename interrogator to client
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/M

#171 Add ListBuilds coverage
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#172 Refactor gcs client out of Build
  cmd/updater/main.go
  pkg/updater/updater.go
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#173 Add methods for reading builds from GCS.
  .bazelignore
  pkg/updater/BUILD.bazel
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/XL

#174 Add ReadColumns coverage.
  go.mod
  pkg/updater/BUILD.bazel
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/XL
