Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-03, with the labels that each got.

#103 Continuing using gcs_prefix externally
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/updater/updater.go
Labels: approved, lgtm, size/L

#104 Validate things are balanced and not empty.
  config/config.go
  config/config_test.go
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/L

#105 Remove oneof for column headers
  config/config.go
  config/config_test.go
  config/yamlcfg/yaml2proto_test.go
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/XL

#106 Ensure yaml config parses correctly.
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/L

#107 Testgrid does not accept gs:// prefix on gcs_prefix field
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/XS

#108 Advanced configuration option validation.
  config/config.go
  config/config_test.go
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/XXL

#110 Config proto should be passed by reference.
  config/config.go
  config/config_test.go
  config/yamlcfg/yaml2proto.go
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/L

#111 Adding Search function to the resultstore client.
  resultstore/BUILD.bazel
  resultstore/client.go
  resultstore/client_test.go
  resultstore/resultstore.go
Labels: approved, lgtm, size/L
