Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-10, with the labels that each got.

#241 Use cmp.Diff with sorting in tests to reduce test flakiness
  pkg/summarizer/flakiness_test.go
Labels: approved, lgtm, size/S

#242 Add properties to alert info.
  pb/state/state.pb.go
  pb/state/state.proto
Labels: approved, lgtm, size/L

#243 Add infra failures to summary proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/analyzers/BUILD.bazel
  pkg/summarizer/analyzers/baseanalyzer.go
  pkg/summarizer/analyzers/baseanalyzer_test.go
  pkg/summarizer/analyzers/flipanalyzer_test.go
  pkg/summarizer/flakiness.go
Labels: approved, lgtm, size/L

#246 Add more prominent information about UI changes
  build_test_update.md
Labels: approved, lgtm, size/XS

#247 Add properties to failing test summaries.
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#249 Add an is_flakiness_bug field to the IssueInfo proto
  pb/issue_state/issue_state.pb.go
  pb/issue_state/issue_state.proto
Labels: approved, lgtm, size/M

#251 Update canary to v20201013-v0.0.24-7-gdc1cc49
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#252 Handle xml documents with invalid utf-8 messages
  metadata/junit/junit.go
  metadata/junit/junit_test.go
Labels: approved, lgtm, size/M

#253 Update canary to v20201015-v0.0.25-2-g481a3cb
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#254 Promote v20201015-v0.0.25-2-g481a3cb to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#255 Handle GCS prefix returning earlier builds
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#256 Upgrade canary to v20201020-v0.0.25-8-g957c387
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#257 Improve updater documentation
  cmd/updater/README.md
Labels: approved, lgtm, size/M

#258 Promote v20201020-v0.0.25-8-g957c387 to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#259 Link to state proto
  cmd/updater/README.md
Labels: approved, lgtm, size/XS

#260 Only process kubernetes client groups.
  cmd/updater/main.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#262 Make results Lte and Gte not stutter.
  internal/result/results.go
Labels: approved, lgtm, size/S
