Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-11, with the labels that each got.

#265 Handle gcs.ResolveReference() errors.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XS

#263 Fix function comment and capitalization.
  internal/result/results.go
Labels: approved, lgtm, size/S

#264 Refactor update to allow control over updateGroup.
  cmd/updater/main.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#266 Fix IsPassingResult() and Coalesce().
  internal/result/BUILD.bazel
  internal/result/results.go
  internal/result/results_test.go
Labels: approved, lgtm, size/L

#268 Switch some proto args to *proto
  cmd/updater/main.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#271 Update alerts in protos with hotlist IDs.
  pb/state/state.pb.go
  pb/state/state.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
Labels: approved, lgtm, size/L

#270 Allow local defaults for a config directory.
  WORKSPACE
  config/yamlcfg/BUILD.bazel
  config/yamlcfg/yaml2proto.go
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/L

#272 Write hotlist IDs to summary.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/XS

#274 Update state.proto to include user_property field.
  pb/state/state.pb.go
  pb/state/state.proto
Labels: approved, lgtm, size/L

#275 Update fields in HealthAnalysisOptions
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L
