Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-04, with the labels that each got.

#116 Populates Dashboard Name in generated summaries
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/S

#117 Make resultstore search project specific
  resultstore/client.go
Labels: approved, lgtm, size/XS

#118 Add README for the resultstore client
  resultstore/README.md
Labels: approved, lgtm, size/M
