Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-01, with the labels that each got.

#76 Add the properties field for the Target struct
  resultstore/resultstore.go
Labels: approved, lgtm, size/XS

#79 Update testgrid to v0.0.1-alpha.4
  cluster/summarizer_deployment.yaml
  cluster/updater_deployment.yaml
Labels: approved, lgtm, size/XS

#80 Add unit test for the fromTarget function
  resultstore/resultstore.go
  resultstore/resultstore_test.go
Labels: approved, lgtm, size/L

#81 Check in service account declarations
  cluster/summarizer_serviceaccount.yaml
  cluster/updater_serviceaccount.yaml
Labels: approved, lgtm, size/S

#82 Always configure docker
  images/push.sh
Labels: approved, lgtm, size/XS

#83 Add deploy script
  cluster/deploy.sh
Labels: approved, lgtm, size/M

#84 Correct deploy.sh documentation
  cluster/deploy.sh
Labels: approved, lgtm, size/XS

#86 Remove apimachinery dependency
  WORKSPACE
  go.mod
  go.sum
  repos.bzl
  resultstore/BUILD.bazel
  resultstore/resultstore_test.go
Labels: approved, lgtm, size/L

#87 Update config.proto with different ColumnHeader options
  cmd/updater/main.go
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#89 Add file_overall option.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L
