Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-06, with the labels that each got.

#125 Add failure Ratios to summary pb
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
Labels: approved, lgtm, ok-to-test, size/L

#126 Fix TestGrid capitalization and hyperlink issues
  README.md
  config.md
Labels: approved, lgtm, ok-to-test, size/S

#127 Add new parameter to the Autobug Config so that each TestGroups
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, ok-to-test, size/L

#129 Add new BROKEN Tab status
  pb/summary/summary.pb.go
  pb/summary/summary.proto
Labels: approved, lgtm, ok-to-test, size/M

#135 Add placeholder method for building FailingTestLinks
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, ok-to-test, size/S

#132 Updating config.proto.
  pb/config/config.pb.go
  pb/config/config.proto
  pb/state/state.proto
Labels: approved, lgtm, size/XL

#136 Update config.proto with new AutoBug options.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#133 Logic to set a Tab Summary overall Status to BROKEN
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, ok-to-test, size/L

#138 Update boilerplate template and file headers to use "The Testgrid Authors"
  CONTRIBUTING.md
  hack/BUILD.bazel
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.generated.go.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/verify_boilerplate.py
  pb/config/config.pb.go
  pb/custom_evaluator/custom_evaluator.pb.go
  pb/issue_state/issue_state.pb.go
  pb/response/types.pb.go
  pb/response/types.proto
  pb/state/state.pb.go
  pb/summary/summary.pb.go
  pb/test_status/test_status.pb.go
  pb/updater/updater.pb.go
Labels: approved, lgtm, size/M

#128 Add some Flakiness Report logic to Summarizer
  pb/summary/BUILD.bazel
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/common/BUILD.bazel
  pkg/summarizer/common/common.go
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/naiveanalyzer/BUILD.bazel
  pkg/summarizer/naiveanalyzer/analyzer.go
  pkg/summarizer/naiveanalyzer/analyzer_test.go
Labels: approved, lgtm, ok-to-test, size/XXL
