Repository GoogleCloudPlatform/testgrid, pull requests merged in 2020-08, with the labels that each got.

#175 Refactor updater to use inflatedColumn.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XXL

#176 Add constructGrid and testGroupPath
  pkg/updater/BUILD.bazel
  pkg/updater/read.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#158 Add fields and logic to summarizer to also record previous flakiness values
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#177 Add updateGroup() coverage
  metadata/job.go
  metadata/job_test.go
  pkg/updater/gcs.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#178 Add coverage for linked builds
  util/gcs/BUILD.bazel
  util/gcs/read_test.go
Labels: approved, lgtm, size/S

#179 Filter test methods out of summaries.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/M

#181 Only reprocess last 4 hours of results
  cmd/updater/main.go
  config/config.go
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/inflate.go
  pkg/updater/read.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/BUILD.bazel
  util/gcs/client.go
Labels: approved, lgtm, size/XL

#182 Update canary to v20200804-v0.0.15-29-g09b67a9
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#187 Fix lint errors across files
  internal/result/results.go
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/summary_test.go
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XXL

#185 Fix race condition when multiple go-routines reach an old build
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#183 Promote v20200804-v0.0.15-29-g09b67a9 to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#189 Refactor Objects() to include an optional start offset
  go.mod
  go.sum
  pkg/updater/read_test.go
  pkg/updater/updater.go
  repos.bzl
  util/gcs/client.go
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#191 Correct --config flag
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#192 Allow k8s-testgrid when gridPrefix is filled.
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  cmd/updater/main_test.go
Labels: approved, lgtm, size/L

#190 Update canary to v20200805-v0.0.15-41-g8f1a867
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#188 Add a flag to enable trace logging
  cmd/updater/main.go
Labels: approved, lgtm, size/S

#193 Update canary to v20200806-v0.0.16-8-g15e7668
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#196 Limit the number of concurrent junit downloads in a single build.
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/M

#195 Upgrade prod to v20200806-v0.0.16-8-g15e7668
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#197 Update canary to v20200806-v0.0.16-12-g054d30c.
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#198 Add ability to track latest-found failure in alerts.
  pb/state/state.pb.go
  pb/state/state.proto
Labels: approved, lgtm, size/L

#199 Promote v20200806-v0.0.16-12-g054d30c to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#200 Reduce canary updater sleep cycle to 5m
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#202 Run the garbage collector after updating each group.
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#201 Continue reprocessing results until they are no longer running.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#203 Upgrade canary to v20200807-v0.0.17-8-gd205182
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#205 Promote v20200807-v0.0.17-8-gd205182 to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#204 Add Ethan to approvers.
  OWNERS
Labels: approved, lgtm, size/XS

#206 Create a beta-summarizer in canary.
  cluster/canary/summarizer.yaml
Labels: approved, lgtm, size/M

#207 Filter out methods via either display or test name.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/XS

#208 Add latest fail build ID to summary.
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#209 Record all issues linked to a tab in summary.
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#210 Add channel label to canary summarizers
  cluster/canary/summarizer.yaml
Labels: approved, lgtm, size/XS

#212 Update to rules_k8s v0.5
  WORKSPACE
  cluster/canary/summarizer.yaml
Labels: approved, lgtm, size/S

#214 Support junit file names that do not match the regex.
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/S

#216 Add a beta summarizer to prod
  cluster/prod/summarizer.yaml
Labels: approved, lgtm, size/M

#217 Dedup summarizer names
  cluster/prod/summarizer.yaml
Labels: approved, lgtm, size/XS

#215 Update canary to v20200819-v0.0.20-5-g6f7e6
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#218 Update canary to v20200819-v0.0.20-5-g6f7e65b
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#219 Promote v20200819-v0.0.20-5-g6f7e65b to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#221 Parse empty junit files as an empty Suites.
  metadata/junit/BUILD.bazel
  metadata/junit/junit.go
  metadata/junit/junit_test.go
Labels: approved, lgtm, size/L

#223 Avoid potential divide by zero operations
  pkg/summarizer/naiveanalyzer/analyzer.go
Labels: approved, lgtm, size/XS

#222 Update canary to v20200821-v0.0.20-17-g7748a00
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#224 Write a new flakiness algorithm for the summarizer
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/analyzers/BUILD.bazel
  pkg/summarizer/analyzers/baseanalyzer.go
  pkg/summarizer/analyzers/baseanalyzer_test.go
  pkg/summarizer/analyzers/flipanalyzer.go
  pkg/summarizer/analyzers/flipanalyzer_test.go
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/summary.go
Labels: approved, lgtm, size/L
