Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-05, with the labels that each got.

#451 Remove unused column_sort_by field
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#452 Allow custom sorting mechanics.
  cmd/updater/main.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#454 Stop assuming the largest hint and start time is the first column.
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/L

#456 Add CellID when commit_override_strftime is set
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
Labels: approved, lgtm, size/M

#455 Correct error message
  hack/compare_states_test.go
Labels: approved, lgtm, size/XS

#458 Set summarized path correctly
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#463 Correct name for grouping.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#462 Stop flaky/pass overall status after num_columns_recent filled columns.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#467 Drop use_configuration_values_as_alert_params
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#460 Implement json un-/marshalling for gcs.Path.
  pkg/summarizer/summary.go
  pkg/updater/updater_test.go
  util/gcs/gcs.go
Labels: approved, lgtm, size/M

#470 Correct disable_merged_status and disable_prowjob_analysis field numb…
  config/config.go
  config/config_test.go
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/updater/read.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XL

#469 Reduce reprocessing time.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#468 Ensure context has something to read.
  pkg/updater/read_test.go
Labels: approved, lgtm, size/XS

#473 Add support for user_property field.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/read.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#465 Add some documentation to overallStatus()
  pkg/summarizer/summary.go
Labels: approved, lgtm, size/S

#474 Delete custom_result_evaluator_rules.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#479 Remove last_alert_mail_time from state
  pb/state/state.pb.go
  pb/state/state.proto
Labels: approved, lgtm, size/L

#480 Refactor readColumns to only error if all columns fail.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/L

#484 Handle edge cases for failed builds.
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#483 Allow cells to collect capture associated issues.
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#487 Allow go programs to access local filesystems through Bazel
  BUILD.bazel
  config/print/README.md
Labels: approved, lgtm, size/S

#488 API Draft
  pb/BUILD.bazel
  pb/api/v1/BUILD.bazel
  pb/api/v1/data.pb.go
  pb/api/v1/data.proto
Labels: approved, lgtm, size/XL

#494 MergeCells needs to merge issues
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/M

#493 Use pointer to grid proto
  pkg/updater/inflate_test.go
Labels: approved, lgtm, size/S
