Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-06, with the labels that each got.

#496 Export MarshalGrid.
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/BUILD.bazel
  util/gcs/gcs.go
  util/gcs/gcs_test.go
Labels: approved, lgtm, size/L

#497 Export InflateGrid.
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/updater.go
Labels: approved, lgtm, size/S

#495 Allow percent difference when comparing states.
  hack/BUILD.bazel
  hack/compare_states.go
  hack/compare_states_test.go
Labels: approved, lgtm, size/L

#498 Lint fixes
  hack/compare_states.go
  util/gcs/gcs.go
Labels: approved, lgtm, size/S

#486 Add new link templates to use when diffing between columns
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, ok-to-test, size/L

#502 Add log-only metric reporter.
  BUILD.bazel
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  util/metrics/BUILD.bazel
  util/metrics/log.go
  util/metrics/log_test.go
  util/metrics/metrics.go
Labels: approved, lgtm, size/L

#506 Add disable_prowjob_analysis to config.md
  config.md
Labels: approved, lgtm, size/S

#508 Fix lint issues in the repo.
  config/config.go
  config/config_test.go
  config/print/main.go
  config/yamlcfg/yaml2proto.go
  metadata/job.go
  pkg/updater/gcs.go
  resultstore/resultstore.go
  util/gcs/fake/fake.go
  util/gcs/gcs.go
  util/metrics/log.go
Labels: approved, lgtm, size/L

#510 Reserve field two of issue state
  pb/issue_state/issue_state.pb.go
  pb/issue_state/issue_state.proto
Labels: approved, lgtm, size/M

#513 Export ConstructGrid.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/S

#511 Add basic success/error metrics for components.
  cmd/config_merger/BUILD.bazel
  cmd/config_merger/main.go
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/updater/main.go
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/metrics/log.go
  util/metrics/log_test.go
  util/metrics/metrics.go
Labels: approved, lgtm, size/L

#512 Refactor writes to return new object metadata.
  pkg/merger/merger.go
  pkg/merger/merger_test.go
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  util/gcs/client.go
  util/gcs/fake/fake.go
  util/gcs/fake/sort_test.go
  util/gcs/gcs.go
  util/gcs/local_gcs.go
  util/gcs/real_gcs.go
  util/gcs/sort.go
Labels: approved, lgtm, size/L

#514 Fix lint errors, again.
  pkg/summarizer/summary.go
  pkg/updater/updater.go
  util/gcs/fake/fake.go
Labels: approved, lgtm, size/S

#509 Optionally print all config fields and # of uses.
  config/print/main.go
Labels: approved, lgtm, size/M

#515 Move progress log into an exported function.
  BUILD.bazel
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  util/BUILD.bazel
  util/log.go
Labels: approved, lgtm, size/L

#518 Escape buildFailLink
  pkg/summarizer/summary.go
Labels: approved, lgtm, size/XS

#503 Parallelize Config Merger
  cmd/config_merger/main.go
  pkg/merger/merger.go
Labels: approved, lgtm, size/M

#520 Add Protocol Buffer Readme
  pb/README.md
Labels: approved, lgtm, size/M

#516 Test grid dynamic email list.
  pb/state/state.pb.go
  pb/state/state.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, ok-to-test, size/L

#519 Refactor Opener interface to return attributes.
  config/config.go
  hack/compare_states.go
  pkg/merger/merger_test.go
  pkg/summarizer/summary.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/client.go
  util/gcs/fake/fake.go
  util/gcs/gcs.go
  util/gcs/local_gcs.go
  util/gcs/read.go
  util/gcs/read_test.go
  util/gcs/real_gcs.go
Labels: approved, lgtm, size/M
