Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-02, with the labels that each got.

#357 Allow test case properties to format name.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/M

#359 Allow row names to use test properties
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#349 Create config merger controller
  BUILD.bazel
  cmd/config_merger/BUILD.bazel
  cmd/config_merger/README.md
  cmd/config_merger/main.go
  go.mod
  pkg/merger/BUILD.bazel
  pkg/merger/merger.go
  pkg/merger/merger_test.go
Labels: approved, lgtm, size/XL

#365 Add latest test ID/link for alerts.
  pb/state/state.pb.go
  pb/state/state.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#364 Add config_merger to image repository
  images/BUILD.bazel
Labels: approved, lgtm, size/XS

#366 Specify protocmp for cmp.Diff.
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/XS

#368 Fix link to config protos.
  standalone.md
Labels: approved, lgtm, size/XS

#369 Update broken-state calculation with neutral statuses.
  internal/result/results.go
  internal/result/results_test.go
  pkg/summarizer/flakiness.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: approved, lgtm, size/L

#370 fix: link to configuration from standalone docs
  standalone.md
Labels: approved, lgtm, ok-to-test, size/XS

#371 Multi job groups: Add job overall row, set cellID
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#273 Change config to reject invalid fields for yaml
  config/yamlcfg/yaml2proto.go
  config/yamlcfg/yaml2proto_test.go
Labels: approved, lgtm, size/M

#373 Only read cell_id from filled columns
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
Labels: approved, lgtm, size/M

#372 Add local filesystem capability to util/gcs.
  go.sum
  pkg/merger/BUILD.bazel
  pkg/merger/merger_test.go
  util/gcs/BUILD.bazel
  util/gcs/client.go
  util/gcs/gcs.go
  util/gcs/gcs_test.go
  util/gcs/local_gcs.go
  util/gcs/real_gcs.go
Labels: approved, lgtm, size/L

#374 Add latest cell and build ID to failures.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#376 Have Summarizer use util/gcs library, not storage itself.
  cmd/summarizer/main.go
  pkg/summarizer/summary.go
Labels: approved, lgtm, size/S

#377 Add updater and summarizer for supporting knative
  cluster/prod/BUILD.bazel
  cluster/prod/knative/namespace.yaml
  cluster/prod/knative/summarizer.yaml
  cluster/prod/knative/updater.yaml
Labels: approved, lgtm, size/L

#375 Merge together all rows with the same name
  hack/update-protos.sh
  internal/result/results.go
  internal/result/results_test.go
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/summarizer/summary.go
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XXL

#380 Only lock when we will write state
  cmd/updater/main.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XS

#381 Hack listing to handle sequential build numbers
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#382 Inject a Pod row into results
  go.mod
  go.sum
  pkg/updater/BUILD.bazel
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater_test.go
  repos.bzl
  util/gcs/BUILD.bazel
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/XL
