Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-04, with the labels that each got.

#410 Stop requiring optional cell ID field when alerting a row.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/S

#412 Handle empty json files.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#414 Malformed junit files should fail the build but not the job.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/M

#400 Add Config Merger for k8s in Canary
  cluster/canary/config_merger.yaml
  cmd/config_merger/main.go
Labels: approved, lgtm, size/M

#417 Use --json-logs for updater, prepare to do so for summarizer
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
  cmd/summarizer/main.go
  cmd/updater/main.go
Labels: approved, lgtm, size/M

#419 Only log the entire summary proto when confirm is false.
  pkg/summarizer/summary.go
Labels: approved, lgtm, size/XS

#421 Use json logs for the summarizer
  cluster/canary/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: approved, lgtm, size/XS

#422 Read JUnit 'error' cases as failures.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/S

#426 Update Config Merger SA
  cluster/canary/config_merger.yaml
  cluster/prod/config_merger.yaml
Labels: approved, lgtm, size/XS

#427 Drop unused gather_test_properties field.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#428 Add example of onboarding testgrid as a service from prow
  standalone.md
Labels: approved, lgtm, size/S

#429 Print Config Utility
  config/BUILD.bazel
  config/print/BUILD.bazel
  config/print/README.md
  config/print/main.go
Labels: approved, lgtm, size/L

#430 Allow MergeCells to fail results with passes.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/M

#431 Document MergeCells and SplitCells.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/M

#433 Modify TruncateRunning to truncate any running cell
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#434 Support commit_override_strftime
  cmd/updater/main_test.go
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XL

#436 Use json logs on knative shard
  cluster/prod/knative/summarizer.yaml
  cluster/prod/knative/updater.yaml
Labels: approved, lgtm, size/XS

#437 Keep running columns many days old.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#439 Implement ignore_old_results.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#443 Summarize tab by least recently updated order.
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/BUILD.bazel
  util/gcs/fake/BUILD.bazel
  util/gcs/fake/fake.go
  util/gcs/fake/fake_test.go
  util/gcs/fake/sort_test.go
  util/gcs/sort.go
Labels: approved, lgtm, size/XXL

#440 Restrict cell and inflatedColumn aliases to unit tests.
  pkg/updater/gcs.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/read.go
  pkg/updater/updater.go
Labels: approved, lgtm, size/M

#446 Move Sort() into sort.go.
  util/gcs/BUILD.bazel
  util/gcs/read.go
  util/gcs/sort.go
  util/gcs/sort_test.go
Labels: approved, lgtm, size/L

#448 Correctly group multiple columns together.
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/read.go
  util/gcs/read_test.go
  util/gcs/sort.go
  util/gcs/sort_test.go
Labels: approved, lgtm, size/XL

#445 Remove unused environment_instance field
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L
