Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-09, with the labels that each got.

#684 Fix timestamp assignment from columns
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/S

#686 Add field metrics to config merger
  cmd/config_merger/BUILD.bazel
  cmd/config_merger/main.go
  config/BUILD.bazel
  config/fields.go
  config/fields_test.go
  go.sum
  pkg/merger/merger.go
  pkg/merger/merger_test.go
Labels: lgtm, approved, size/L

#688 Add repeated key-value pairs for cells in state.
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/updater/inflate.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/XL

#689 Don't store properties on group-delimiter rows.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#690 Truncate long messages when storing in state.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#692 Increase CPU, RAM and --build-concurrency
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/S

#693 Tune canary concurrency, timeout, ram, cpu
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/S

#694 Tune prod updater.
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/S

#695 Allow InflateGrid to time out.
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/updater.go
Labels: lgtm, approved, size/M

#698 Populate FailBuildID based on data source
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/summarizer/summary.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/XL

#701 Upload an empty grid state for new test groups
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/fake/fake.go
  util/gcs/fake/sort_test.go
Labels: lgtm, approved, size/L

#704 Pass bug URL to summary when specified.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/L

#706 Refactor inflation to use callback iteration rather than channels
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
Labels: lgtm, approved, size/L

#707 Add BenchmarkInflateGrid
  pkg/updater/BUILD.bazel
  pkg/updater/inflate_test.go
Labels: lgtm, approved, size/M

#709 Always include job name on Overall row.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read_test.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L
