Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-12, with the labels that each got.

#772 Unescape local filepaths.
  util/gcs/BUILD.bazel
  util/gcs/local_gcs.go
  util/gcs/local_gcs_test.go
Labels: lgtm, approved, size/M

#773 Remove messages, properties, metrics before other column data
  pkg/updater/inflate.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#776 Add testgrid-base-options to config.md
  config.md
Labels: lgtm, approved, size/XS, needs-ok-to-test
