Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-11, with the labels that each got.

#738 Truncate grid more aggressively.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#739 Add AutoBug option to ignore overall rows.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L

#740 Log when we successfully summarize a dashboard.
  pkg/summarizer/summary.go
Labels: lgtm, approved, size/XS

#741 Allow summarizer to repeat --dashboard flag
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  cmd/updater/main_test.go
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  util/BUILD.bazel
  util/strings.go
Labels: lgtm, approved, size/L

#742 Convert config_merger logging to use Prometheus
  cmd/config_merger/BUILD.bazel
  cmd/config_merger/main.go
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  go.mod
  go.sum
  repos.bzl
  util/metrics/BUILD.bazel
  util/metrics/logmetrics/BUILD.bazel
  util/metrics/logmetrics/log.go
  util/metrics/logmetrics/log_test.go
  util/metrics/prometheus/BUILD.bazel
  util/metrics/prometheus/prometheus.go
  util/metrics/prometheus/prometheus_test.go
Labels: lgtm, approved, size/XL

#746 Add Pod Monitors to Config Merger
  cluster/canary/config_merger.yaml
  cluster/canary/monitoring.yaml
  cluster/prod/config_merger.yaml
  cluster/prod/monitoring.yaml
Labels: lgtm, approved, size/M

#747 Refactor summarizer to be more efficient.
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/fake/sort_test.go
  util/gcs/sort.go
Labels: lgtm, approved, size/XL

#748 Convert all controllers to emit prometheus metrics
  cluster/canary/monitoring.yaml
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
  cluster/prod/monitoring.yaml
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
Labels: lgtm, approved, size/L

#749 Revert "Bumping Testgrid Prod"
  cluster/prod/config_merger.yaml
  cluster/prod/knative/summarizer.yaml
  cluster/prod/knative/updater.yaml
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/S

#750 Make prometheus metrics safe for concurrency
  util/metrics/prometheus/prometheus.go
Labels: lgtm, approved, size/S

#754 Support merging columns with more/fewer column headers.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#753 Add concurrence-safety tests to prometheus metrics
  util/metrics/prometheus/prometheus_test.go
Labels: lgtm, approved, size/M

#759 Limit grid state to 2mb
  pkg/updater/updater.go
Labels: lgtm, approved, size/XS

#761 Standardize cycle metrics across controllers
  cmd/config_merger/BUILD.bazel
  cmd/config_merger/main.go
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  pkg/merger/BUILD.bazel
  pkg/merger/merger.go
  pkg/merger/merger_test.go
  pkg/summarizer/summary.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/metrics/BUILD.bazel
  util/metrics/metrics.go
  util/metrics/metrics_test.go
Labels: lgtm, approved, size/L

#762 Prevent concurrently updating the same dashboard.
  pkg/summarizer/summary.go
Labels: lgtm, approved, size/M

#758 Initialize queues with a logger
  config/BUILD.bazel
  config/queue.go
  config/queue_test.go
  pkg/summarizer/summary.go
  pkg/updater/pubsub_test.go
  pkg/updater/updater.go
  util/BUILD.bazel
  util/queue.go
  util/queue_test.go
Labels: lgtm, approved, size/L

#766 Use Factory in metric generation for config_merger
  pkg/merger/BUILD.bazel
  pkg/merger/merger.go
  pkg/updater/updater.go
Labels: lgtm, approved, size/XS

#767 Testgrid autobump PR not assigned to oncall
  cluster/testgrid-canary-autobump-config.yaml
  cluster/testgrid-prod-autobump-config.yaml
Labels: lgtm, approved, size/XS

#769 Create Duration metric
  cmd/config_merger/BUILD.bazel
  cmd/config_merger/main.go
  cmd/summarizer/BUILD.bazel
  cmd/summarizer/main.go
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  pkg/updater/updater.go
  util/metrics/metrics.go
  util/metrics/metrics_test.go
  util/metrics/prometheus/prometheus.go
  util/metrics/prometheus/prometheus_test.go
Labels: lgtm, approved, size/L

#770 Improve summarizer logging.
  pkg/summarizer/summary.go
Labels: lgtm, approved, size/M

#771 Fix timestamp misconversion
  pkg/api/v1/state.go
  pkg/api/v1/state_test.go
Labels: lgtm, approved, size/M
