Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-08, with the labels that each got.

#600 Periodically update generations.
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#601 Inability to find a bucket should not be an error
  pkg/updater/read.go
  pkg/updater/updater_test.go
  util/gcs/fake/fake.go
Labels: approved, lgtm, size/M

#605 Run GC after updating a test group
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#604 Limit the amount of time spent shrinking.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#606 Detect wrapped precondition errors
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#609 Track groups that are updating.
  pkg/updater/updater.go
Labels: approved, lgtm, size/M

#613 Move API canary to GKE Ingress
  cluster/canary/api.yaml
Labels: approved, lgtm, size/M

#602 TestGrid Dynamic List - support extract email list from []interface{}
  metadata/job.go
  metadata/job_test.go
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, ok-to-test, size/L

#614 Add namespace to ingress
  cluster/canary/api.yaml
Labels: approved, lgtm, size/XS

#616 Allow only reducing the time for a queued item.
  config/queue.go
  config/queue_test.go
  pkg/updater/updater.go
Labels: approved, lgtm, size/L

#615 Add implementation for these config APIs
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
Labels: lgtm, approved, size/L, ok-to-test

#618 Initial pubsub package
  .bazelversion
  BUILD.bazel
  WORKSPACE
  go.mod
  go.sum
  pb/api/v1/data.pb.go
  pb/config/config.pb.go
  pb/custom_evaluator/custom_evaluator.pb.go
  pb/issue_state/issue_state.pb.go
  pb/response/types.pb.go
  pb/state/state.pb.go
  pb/summary/summary.pb.go
  pb/test_status/test_status.pb.go
  pb/updater/updater.pb.go
  pkg/pubsub/BUILD.bazel
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_test.go
  repos.bzl
Labels: lgtm, approved, size/XXL

#619 Correct flag to enable race detction during testing.
  .bazelrc
Labels: lgtm, approved, size/XS

#621 Script to create testgrid variant of gcloud-bazel image
  images/gcloud-bazel/.gitignore
  images/gcloud-bazel/push.sh
Labels: lgtm, approved, size/S

#623 Document pubsub package
  pkg/pubsub/pubsub.go
Labels: lgtm, approved, size/XS

#628 Reduce Roused logging noisiness.
  config/queue.go
Labels: lgtm, approved, size/S

#627 Ensure offset has a trailing /.
  util/gcs/read.go
Labels: lgtm, approved, size/XS

#629 Refactor pubsub package for easier unit testing.
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_test.go
Labels: lgtm, approved, size/M

#631 Allow updater to subscribe to pubsub notifiations.
  cmd/updater/BUILD.bazel
  cmd/updater/main.go
  metadata/README.md
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/pubsub/pubsub.go
  pkg/updater/BUILD.bazel
  pkg/updater/pubsub.go
  pkg/updater/pubsub_test.go
  pkg/updater/read.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/XXL

#632 Sort subscriptions (for determinism)
  pkg/updater/pubsub_test.go
Labels: lgtm, approved, size/S

#633 Add FixGCS unit test coverage
  pkg/updater/BUILD.bazel
  pkg/updater/pubsub.go
  pkg/updater/pubsub_test.go
Labels: lgtm, approved, size/L

#638 Update setup-pubsub.sh to configure IAM
  cluster/create-subscription.sh
  cluster/setup-pubsub.sh
Labels: lgtm, approved, size/M

#636 Add manual subscriptions to canary.
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#639 Fix canary updater --subscribe flag
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#640 Add subscription field to logs
  pkg/pubsub/pubsub.go
Labels: lgtm, approved, size/XS

#642 Convert subscription field to string
  pkg/updater/pubsub.go
Labels: lgtm, approved, size/XS

#645 Update canary updater flags.
  cluster/canary/updater.yaml
  config/queue.go
Labels: lgtm, approved, size/S

#646 Add --subscribe flags to prod.
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/S

#649 Additional unit tests
  pkg/updater/pubsub_test.go
Labels: lgtm, approved, size/S

#637 Update .bazelrc to allow for the possibility of RBE
  .bazelrc
Labels: lgtm, approved, size/S

#643 Update setup-pubsub.sh for mulitple topics.
  cluster/create-subscription.sh
  cluster/create-topic.sh
  cluster/setup-pubsub.sh
Labels: lgtm, approved, size/M

#651 Match PR directory links.
  pkg/updater/pubsub.go
  pkg/updater/pubsub_test.go
Labels: lgtm, approved, size/M

#655 Remove deprecated beta-summarizer from knative
  cluster/prod/knative/summarizer.yaml
Labels: lgtm, approved, size/M

#657 Allow time to collect podinfo.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/pubsub.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#626 Add implementation for ListHeaders, ListRows
  cmd/api/main.go
  pkg/api/router.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
  pkg/api/v1/state_test.go
Labels: lgtm, approved, size/XL, ok-to-test

#661 Update config APIs response type
  pkg/api/v1/config.go
Labels: lgtm, approved, size/S, needs-ok-to-test

#664 Reduce updater replicas to 1
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#662 Fix a panic in updater (if update errors and freq = 0)
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#660 Add more options for comparing states.
  go.mod
  go.sum
  hack/BUILD.bazel
  hack/compare_states.go
  hack/compare_states_test.go
  repos.bzl
Labels: lgtm, approved, size/XL

#668 Move compare_states.go to cmd/state_comparer.
  BUILD.bazel
  cmd/state_comparer/BUILD.bazel
  cmd/state_comparer/README.md
  cmd/state_comparer/main.go
  cmd/state_comparer/main_test.go
  hack/BUILD.bazel
Labels: lgtm, approved, size/M

#669 Check the correct stat error.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#671 Trace when we connect to pubsub subscriptions
  pkg/pubsub/pubsub.go
Labels: lgtm, approved, size/XS

#677 Stop touching the grid before download, tracking generation.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/gcs.go
Labels: lgtm, approved, size/L

#680 Fix lint error
  pkg/updater/updater.go
Labels: lgtm, approved, size/XS

#678 Configure pubsub for knative testgrid instance
  cluster/prod/knative/OWNERS
  cluster/prod/knative/setup-pubsub.sh
  cluster/prod/knative/updater.yaml
Labels: lgtm, approved, size/M

#681 Reduce to a single updater replica.
  cluster/prod/knative/updater.yaml
Labels: lgtm, approved, size/XS
