Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-07, with the labels that each got.

#521 Fix go lint + vet warnings
  config/print/main.go
  pkg/updater/gcs.go
  pkg/updater/updater_test.go
  util/log.go
Labels: approved, lgtm, size/S

#522 Refactor updater to continually send groups to be updated.
  cmd/updater/main.go
  config/BUILD.bazel
  config/queue.go
  config/queue_test.go
  go.mod
  go.sum
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  repos.bzl
  util/gcs/sort.go
  util/metrics/log.go
Labels: approved, lgtm, size/XXL

#524 Changes to the queue should end sleeps early
  config/queue.go
Labels: approved, lgtm, size/M

#527 Refactor metrics interface.
  cmd/summarizer/main.go
  cmd/updater/main.go
  pkg/updater/updater_test.go
  util/metrics/BUILD.bazel
  util/metrics/log.go
  util/metrics/log_test.go
  util/metrics/metrics.go
Labels: approved, lgtm, size/XL

#530 Refactor logging metrics into a struct.
  cmd/config_merger/main.go
  cmd/summarizer/main.go
  cmd/updater/main.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater_test.go
  util/metrics/log.go
  util/metrics/log_test.go
Labels: approved, lgtm, size/L

#532 Code cleanup.
  config/queue_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/S

#534 Include totals in logged metrics
  util/metrics/log.go
  util/metrics/log_test.go
Labels: approved, lgtm, size/M

#490 Initial API Implementation
  BUILD.bazel
  cmd/api/BUILD.bazel
  cmd/api/main.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  pb/api/v1/data.pb.go
  pb/api/v1/data.proto
  pkg/api/BUILD.bazel
  pkg/api/router.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
  pkg/api/v1/json.go
  repos.bzl
Labels: approved, lgtm, size/XL

#536 Allow specifying multiple test groups to Updater.
  cmd/updater/main.go
  cmd/updater/main_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#537 Lock access to reading the generation.
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#538 Start pushing API image
  cmd/api/BUILD.bazel
  images/BUILD.bazel
Labels: approved, lgtm, size/XS

#540 Pretty-print config by default
  config/print/main.go
Labels: approved, lgtm, size/S

#541 Correct spelling
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#542 Reduce concurrency.
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/S

#544 Refactor ColumnReader to use channels.
  cmd/updater/main.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/metrics/log.go
Labels: approved, lgtm, size/XL

#545 Emit synthetic columns for ancient builds.
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#539 Fix linting and bad copying in api package
  cmd/api/main.go
  pkg/api/router.go
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
Labels: approved, lgtm, size/L

#548 API deployment cluster in canary (only)
  cluster/canary/BUILD.bazel
  cluster/canary/api.yaml
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
Labels: approved, lgtm, size/M

#550 Implement GetDashboardGroup
  go.sum
  pkg/api/router.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
Labels: approved, lgtm, size/L

#552 Specify testgrid-canary namespace
  cluster/canary/api.yaml
Labels: approved, lgtm, size/XS

#553 Use buffered channels instead of concurrency.
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  util/gcs/read.go
  util/gcs/read_test.go
  util/gcs/sort_test.go
Labels: approved, lgtm, size/L

#556 Log when we add/remove/update when we want to update a group
  config/queue.go
Labels: approved, lgtm, size/S

#559 Make fixing group update time less noisy
  config/queue.go
Labels: approved, lgtm, size/S

#561 Check preconditions when reading.
  cmd/updater/main.go
  config/queue.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/BUILD.bazel
  util/gcs/real_gcs.go
Labels: approved, lgtm, size/M

#563 Improve metric strings.
  util/metrics/log.go
  util/metrics/log_test.go
Labels: approved, lgtm, size/M

#564 Synthetic columns are not readColumns errors.
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/M

#567 Allow anyone to create multi-job test groups
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#569 Include number of bytes uploaded in error message.
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#571 Add a random duration before retrying errors.
  pkg/updater/updater.go
Labels: approved, lgtm, size/S

#574 Deflake unit tests.
  pkg/updater/read_test.go
  pkg/updater/updater_test.go
  util/gcs/fake/fake.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/S

#576 Fix a few bugs in config validation.
  config/config.go
  config/config_test.go
Labels: approved, lgtm, size/M

#578 Allocate half the time to compile and upload results.
  pkg/updater/updater.go
Labels: approved, lgtm, size/S

#580 Add option in GetRouter to override the storage client
  cmd/api/main.go
  pkg/api/BUILD.bazel
  pkg/api/router.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#581 Do not use a buffered channel for newCols.
  pkg/updater/updater.go
Labels: approved, lgtm, size/XS

#583 Try and deflake TestReadColumns
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/XS

#585 Move canary to the testgrid auto cluster.
  cluster/canary/BUILD.bazel
  cluster/deploy.sh
  hack/print-workspace-status.sh
Labels: approved, lgtm, size/XS

#584 Ignore columns with no cells.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#586 Prevent divide by zero calculating rate
  util/log.go
Labels: approved, lgtm, size/XS

#589 Modernize summarizer deployment.
  cluster/canary/summarizer.yaml
  cluster/prod/summarizer.yaml
  cmd/summarizer/main.go
Labels: approved, lgtm, size/M

#588 Reduce Sleep info messages to long sleeps
  config/queue.go
Labels: approved, lgtm, size/XS

#590 Stop blunderbussing to Ethan for now
  OWNERS
Labels: approved, lgtm, size/XS

#592 Modernize summarizer for canary too
  cluster/canary/summarizer.yaml
Labels: approved, lgtm, size/M

#593 Configure canary updater resources
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/S

#596 Use the autopilot cluster everywhere
  cluster/canary/BUILD.bazel
  cluster/deploy.sh
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
  hack/print-workspace-status.sh
Labels: approved, lgtm, size/S

#595 Shrink grids to a reasonable size.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#598 Remove unused variable
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XS

#599 Handle unused ctx in test column reader.
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M
