Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-10, with the labels that each got.

#710 Fix latest run timestamp assignment
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/S

#711 Don't consider an alert started until there are enough passes.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#712 Auto-remove excessively large cells
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#714 Refactor TestGroup out of base Queue
  config/BUILD.bazel
  config/queue.go
  config/queue_test.go
  util/BUILD.bazel
  util/queue.go
  util/queue_test.go
Labels: lgtm, approved, size/XXL

#720 Fix unused it var
  util/queue.go
Labels: lgtm, approved, size/S

#725 Store hostname as URL
  cmd/api/main.go
  pkg/api/router.go
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
Labels: lgtm, approved, size/M

#736 Add file_stale option.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L
