Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-01, with the labels that each got.

#317 Always keep at least one preexisting column whenever possible
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/updater.go
Labels: approved, lgtm, size/M

#318 Update canary to v20210105-v0.0.37-4-gfec70c5
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#319 Promote v20210105-v0.0.37-4-gfec70c5 to prod
  cluster/prod/summarizer.yaml
  cluster/prod/updater.yaml
Labels: approved, lgtm, size/XS

#320 Fix unit test error message
  pkg/updater/inflate_test.go
Labels: approved, lgtm, size/XS

#321 Improve sleep message.
  cmd/updater/main.go
Labels: approved, lgtm, size/XS

#322 Make config files needed for autobump
  cluster/testgrid-canary-autobump-config.yaml
  cluster/testgrid-prod-autobump-config.yaml
Labels: approved, lgtm, size/M

#323 Add missing branch field in autobump configs
  cluster/testgrid-canary-autobump-config.yaml
  cluster/testgrid-prod-autobump-config.yaml
Labels: approved, lgtm, size/XS

#324 Remove info for k8s robot from testgrid autobump config
  cluster/testgrid-canary-autobump-config.yaml
  cluster/testgrid-prod-autobump-config.yaml
Labels: approved, lgtm, size/XS

#325 Add configuration merging functions to config library
  config/BUILD.bazel
  config/converge.go
  config/converge_test.go
Labels: approved, lgtm, size/XL

#327 Allow groups to collate multiple prow jobs together.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/XL

#331 no op whitespace change to trigger autobump prod job
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: approved, lgtm, size/XS

#333 Simplify groupPaths errors
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/S

#336 Fix lint errors in config package
  config/converge.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/S

#337 Add an AutoBug option to query the test metadata API.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, size/L

#338 Add documentation for new TestGrid instances
  README.md
  build_test_update.md
  standalone.md
Labels: approved, lgtm, size/M

#339 Deduplicate context declaration in Summarizer
  cmd/summarizer/main.go
Labels: approved, lgtm, size/XS

#344 Add job name when results collate multiple jobs
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  util/gcs/read.go
  util/gcs/read_test.go
Labels: approved, lgtm, size/L

#345 Remove trailing whitespace
  standalone.md
Labels: approved, lgtm, size/XS

#348 Move row rendering logic inside nameConfig
  pkg/updater/gcs.go
  pkg/updater/read.go
  pkg/updater/read_test.go
Labels: approved, lgtm, size/L

#351 Pull numeric junit properties into row metrics.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
Labels: approved, lgtm, size/L

#354 Handle missing passed in finished.json.
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/M
