Repository GoogleCloudPlatform/testgrid, pull requests merged in 2021-03, with the labels that each got.

#387 Only add missing pod info note after job finishes.
  images/push.sh
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/L

#389 Append metrics correctly.
  pkg/updater/inflate.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/M

#392 Fix some lint and unit test errors
  pkg/merger/merger.go
  pkg/summarizer/summary.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/client.go
  util/gcs/gcs.go
  util/gcs/read.go
Labels: approved, lgtm, size/M

#396 Add ability to disable_prowjob_analysis.
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
Labels: approved, lgtm, size/XL

#397 Test analyzeProwJob explicitly
  pkg/updater/gcs_test.go
Labels: approved, lgtm, size/L

#395 Add quick script to compare two TestGrid states.
  hack/BUILD.bazel
  hack/compare_states.go
  hack/compare_states_test.go
  pkg/updater/read.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/gcs/BUILD.bazel
  util/gcs/gcs.go
  util/gcs/local_gcs.go
Labels: approved, lgtm, size/XL

#401 Refactor updater package to target non-GCS results.
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/inflate.go
  pkg/updater/inflate_test.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: approved, lgtm, size/XXL

#404 Validate dashboard name length and dashboardTab length
  config/config.go
  config/config_test.go
Labels: approved, lgtm, size/L

#407 Add a test_method_unmatch_regex field to TestGroup
  pb/config/config.pb.go
  pb/config/config.proto
Labels: approved, lgtm, ok-to-test, size/L

#406 Add JUnit "error" test cases
  metadata/junit/junit.go
  metadata/junit/junit_test.go
Labels: approved, lgtm, ok-to-test, size/M
