Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-05, with the labels that each got.

#935 Move tab alert settings behind a flag
  cmd/tabulator/main.go
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/L

#937 Enable filter-columns on TG Canary
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#938 Filter columns in prod
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#939 Set Tabulator cache settings to "verified cache only"
  pkg/merger/merger.go
  pkg/summarizer/summary.go
  pkg/tabulator/tabstate.go
  pkg/updater/updater.go
  util/gcs/gcs.go
  util/gcs/local_gcs_test.go
  util/gcs/sort.go
  util/queue/persist.go
Labels: lgtm, approved, size/S

#941 Calculate column stats in canary.
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#942 Refactor tabulator algorithm to tabulate by test group
  cmd/tabulator/main.go
  pkg/tabulator/persist.go
  pkg/tabulator/pubsub.go
  pkg/tabulator/tabstate.go
Labels: lgtm, approved, size/L

#943 Add benchmark script
  benchmark/tabulator.sh
Labels: lgtm, approved, size/M

#945 Tune tabulator
  cluster/canary/tabulator.yaml
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/S

#947 Set filter by regex as default behavior for tabulator
  cmd/tabulator/main.go
Labels: lgtm, approved, size/XS

#949 Concurrently summarize tabs in a dashboard.
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/L

#950 Track when a dashboard needs more tabs summarized
  pkg/summarizer/summary.go
Labels: lgtm, approved, size/S

#952 Use go for tabulator benchmarking
  .gitignore
  BUILD.bazel
  benchmark/BUILD.bazel
  benchmark/tabulator.sh
  benchmark/tabulator_bench_test.go
Labels: lgtm, approved, size/L

#955 Use --json-logs on kubernetes.
  cluster/canary/tabulator.yaml
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/S

#953 Remove filter flag from canary
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#957 Remove filter flag from production
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#959 Default values for --summary-path and --tab-path
  cluster/canary/summarizer.yaml
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
  cmd/api/main.go
  cmd/summarizer/main.go
Labels: lgtm, approved, size/S

#958 Concurrently read GCS builds when requested
  cmd/updater/main.go
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#962 Fix typos, non-ref pb
  config/cache.go
  pkg/api/v1/config.go
  pkg/api/v1/state.go
  pkg/summarizer/summary.go
  pkg/updater/read_test.go
  pkg/updater/updater.go
  util/gcs/gcs.go
  util/metrics/prometheus/prometheus.go
Labels: lgtm, approved, size/M

#961 Turn on pooled updating in canary.
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#965 Stop setting --tab-path to its default value
  cluster/canary/api.yaml
  cluster/canary/summarizer.yaml
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#966 Retire --grid-path flag from summarizer
  cluster/canary/summarizer.yaml
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
  cmd/summarizer/main.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/L

#968 Drop copyOnly support for tabulator
  benchmark/tabulator_bench_test.go
  cmd/tabulator/main.go
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
Labels: lgtm, approved, size/M

#970 Only serialize reads of many builds
  pkg/updater/read.go
Labels: lgtm, approved, size/XS

#972 Add flag to turn off forced GC
  cmd/updater/main.go
  pkg/updater/updater.go
Labels: lgtm, approved, size/XS

#971 Improve Iter() performance.
  internal/result/results.go
  internal/result/results_test.go
  pkg/summarizer/flakiness.go
  pkg/summarizer/flakiness_test.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  pkg/updater/updater.go
Labels: lgtm, approved, size/L

#973 Refactor benchmark to be table driven.
  internal/result/results_test.go
Labels: lgtm, approved, size/M

#977 Enable --skip-gc in canary
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#978 Drop --grid-path flag and remaining usage.
  cmd/summarizer/main.go
  pkg/summarizer/pubsub.go
Labels: lgtm, approved, size/S

#980 Lint fixes
  internal/result/results.go
  pkg/updater/updater.go
Labels: lgtm, approved, size/S

#981 Use --build-concurrency, default --pooled=true
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
  cmd/updater/main.go
  cmd/updater/main_test.go
Labels: lgtm, approved, size/S

#982 Add --skip-gc to prod
  cluster/prod/knative/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#948 Refactor Tabulator to read and write in separate pools
  .gitignore
  benchmark/tabulator_bench_test.go
  cmd/tabulator/main.go
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/L

#985 Remove --pooled, --skip-gc (defaults true)
  cluster/canary/updater.yaml
  cluster/prod/knative/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#986 Calculate column stats in prod.
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#987 Set maximum delay to twice the update frequency
  pkg/updater/updater.go
Labels: lgtm, approved, size/XS

#988 Remove --pooled flag
  cmd/updater/main.go
  cmd/updater/main_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#990 Check whether the config snapshot channel is closed
  pkg/updater/updater.go
Labels: lgtm, approved, size/XS

#991 Remove --reprocess-on-change flag
  cluster/canary/updater.yaml
  cluster/prod/knative/updater.yaml
  cluster/prod/updater.yaml
  cmd/updater/main.go
  cmd/updater/main_test.go
Labels: lgtm, approved, size/M

#992 Retire basicResultReader
  pkg/updater/read.go
  pkg/updater/read_test.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#995 add attributes from reading configuration
  config/cache.go
  config/cache_test.go
  pkg/api/v1/config.go
  pkg/merger/merger.go
Labels: lgtm, approved, size/M, ok-to-test
