Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-06, with the labels that each got.

#998 Remove --skip-gc and --reprocess-on-change flags
  cmd/updater/main.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/M

#994 Truncate testgroup state inline
  cmd/updater/main.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#1004 Fix test group config in task creation in tabulator
  benchmark/tabulator.sh
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/M

#891 Add skip-filter flag for summarizer
  cmd/summarizer/main.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/L

#1006 Enable features in canary
  cluster/canary/summarizer.yaml
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#1009 Re-enable filter columns in production
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#1010 Stop filtering by regex in prod summarizer
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#1011 Shrink inline for production updaters
  cluster/prod/knative/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#1014 Seed prow inrepoconfig job
  .prow.yaml
Labels: lgtm, approved, size/S

#1016 Fix protos
  BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/api/v1/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/api/v1/data.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/config/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/config/config.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/custom_evaluator/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/custom_evaluator/custom_evaluator.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/issue_state/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/issue_state/issue_state.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/response/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/response/types.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/state/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/state/state.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/summary/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/summary/summary.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/test_status/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/test_status/test_status.pb.go
  github.com/GoogleCloudPlatform/testgrid/pb/updater/BUILD.bazel
  github.com/GoogleCloudPlatform/testgrid/pb/updater/updater.pb.go
  hack/update-protos.sh
  pb/api/v1/data.pb.go
  pb/config/config.pb.go
  pb/custom_evaluator/custom_evaluator.pb.go
  pb/issue_state/issue_state.pb.go
  pb/response/types.pb.go
  pb/state/state.pb.go
  pb/summary/summary.pb.go
  pb/test_status/test_status.pb.go
  pb/updater/updater.pb.go
  platform/BUILD.bazel
Labels: lgtm, approved, size/XXL

#1017 modernize .bazelrc
  .bazelrc
Labels: lgtm, approved, size/XS

#1021 Default --shrink-inline to true
  cmd/updater/main.go
Labels: lgtm, approved, size/XS

#1012 add attribute to metrics
  pkg/merger/BUILD.bazel
  pkg/merger/merger.go
  pkg/merger/merger_test.go
Labels: lgtm, approved, size/L

#1025 Allow 0 or -1 component in test metadata options.
  config/config.go
  config/config_test.go
Labels: lgtm, approved, size/M

#1026 Enable broken column calculation in knative prod.
  cluster/prod/knative/tabulator.yaml
Labels: lgtm, approved, size/XS

#1027 Remove --skip-inline flag from cluster
  cluster/canary/updater.yaml
  cluster/prod/knative/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#1028 Switch skip-base-options-filter feature flag to true by default
  cmd/summarizer/main.go
Labels: lgtm, approved, size/XS

#1031 Remove --filter-columns flag
  cluster/canary/tabulator.yaml
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#1032 Use rules_k8s 0.7
  WORKSPACE
Labels: lgtm, approved, size/S

#1033 Correct OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#1037 Remove --skip-base-options-filter flag
  cluster/canary/summarizer.yaml
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#1038 Flip --column-stats true by default.
  cmd/tabulator/main.go
Labels: lgtm, approved, size/XS

#1039 Remove summarizer-side filtering
  cmd/summarizer/main.go
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/L

#1041 Remove customizable sorting from updater
  cmd/updater/main.go
  pb/config/config.proto
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#1043 Use cmp instead of reflect for proto comparision
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/XS
