Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-04, with the labels that each got.

#883 Restore --dashboard functionality.
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/M

#885 Receive all statuses from the column.
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/M

#886 Allow any filter for subscriptions.
  cluster/create-subscription.sh
Labels: lgtm, approved, size/S

#887 Add processing to tabulator
  cmd/tabulator/main.go
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/L

#892 Add --dashboard flag to tabulator
  cmd/tabulator/BUILD.bazel
  cmd/tabulator/main.go
  pkg/tabulator/tabstate.go
Labels: lgtm, approved, size/S

#889 Support reprocessing grid when the config changes
  cmd/updater/main.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#890 Add filtering to tabulator
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/filter.go
  pkg/tabulator/filter_test.go
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/L

#894 Limit reprocessing to certain groups
  cmd/updater/main.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
Labels: lgtm, approved, size/S

#897 Allow a couple groups to reprocess on change
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#898 Fix protocmp in test
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/filter.go
  pkg/tabulator/filter_test.go
Labels: lgtm, approved, size/S

#899 Enable filter in canary
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#900 Reprocess some prod groups on change.
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#901 Reprocess all prod groups on change
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#902 Log when we reprocess a test group
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/XS

#903 Give the canary tabulator updater-like resources
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#905 Drop empty columns after filtering by regex
  cmd/tabulator/main.go
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#906 Add filtering to tabulator production
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/S

#908 Filter columns in tabulator canary
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#909 Filter empty columns in production
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#910 Revert "Filter empty columns in production"
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#912 Alias test_status protobuf
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/L

#911 Revert "Revert "Filter empty columns in production""
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#915 Move inflate behind flag
  pkg/tabulator/tabstate.go
Labels: lgtm, approved, size/S

#916 Revert "Revert "Revert "Filter empty columns in production"""
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#918 Refactor ConstructGrid
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#919 Remove redundant test
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/L

#921 Deprecate test group AutoBug settings.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/XL

#922 Add basic PubSub alerts using Terraform.
  .gitignore
  terraform/Makefile
  terraform/README.md
  terraform/main.tf
  terraform/modules/alerts/main.tf
  terraform/modules/alerts/probers.tf
  terraform/modules/alerts/variables.tf
  terraform/provider.tf
Labels: lgtm, approved, size/L

#925 Set alerts on tabulator while filtering columns
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/L

#926 Remove filter-columns experiment from canary
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#929 Reprocess on changed config by default
  cluster/prod/knative/updater.yaml
  cmd/updater/main.go
  cmd/updater/main_test.go
Labels: lgtm, approved, size/S

#928 Calculate column stats when broken column threshold is specified.
  cmd/tabulator/main.go
  pb/state/state.pb.go
  pb/state/state.proto
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/XL

#931 Validate names only contain allowed characters.
  config/config.go
  config/config_test.go
Labels: lgtm, approved, size/M

#932 Use raw string literal for regex.
  config/config.go
Labels: lgtm, approved, size/XS
