Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-08, with the labels that each got.

#1054 Delete response/types.proto
  pb/BUILD.bazel
  pb/response/BUILD.bazel
  pb/response/types.pb.go
  pb/response/types.proto
Labels: lgtm, approved, size/XXL

#1055 fix: Add skipped status back for Ginkgo v2
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
Labels: lgtm, approved, size/M, ok-to-test

#1056 Added description to DashboardGroup and Dashboard in config.proto
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L, ok-to-test
