Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-01, with the labels that each got.

#777 Added simple autobug field for arbitrary extra text
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L

#778 Document update-protos requiring python2
  build_test_update.md
Labels: lgtm, approved, size/XS

#775 Add cache backing ReadGCS
  config/BUILD.bazel
  config/cache.go
  config/cache_test.go
  config/config.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config_test.go
  pkg/merger/merger_test.go
Labels: lgtm, approved, size/L

#780 Reserve a field for AutoBug options.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L

#783 Allow multiple ccs in default test metadata
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/S

#788 Deduplicate context dependency
  config/snapshot/BUILD.bazel
  config/snapshot/config_snapshot_test.go
  go.mod
Labels: lgtm, approved, size/XS

#790 Move summarizer to config snapshot library
  config/snapshot/config_snapshot.go
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
Labels: lgtm, approved, size/L

#789 Refactor API to support gRPC definitions
  pb/api/v1/BUILD.bazel
  pb/api/v1/data.pb.go
  pb/api/v1/data.proto
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
Labels: lgtm, approved, size/XXL
