Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-03, with the labels that each got.

#835 Point prod Tabulator to prod bucket.
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#836 Add basic instructions for adding a new component to the release.
  cluster/prod/README.md
Labels: lgtm, approved, size/S

#837 Allow tabulator to subscribe to updates
  cmd/tabulator/BUILD.bazel
  cmd/tabulator/main.go
Labels: lgtm, approved, size/M

#838 junit: Use "message" attribute at Message func
  metadata/junit/junit.go
  metadata/junit/junit_test.go
Labels: lgtm, approved, size/L, ok-to-test

#842 Allow local file creation to create nested files
  util/gcs/local_gcs.go
  util/gcs/local_gcs_test.go
Labels: lgtm, approved, size/M

#840 Read tab state from tab state
  cluster/canary/summarizer.yaml
  cluster/prod/summarizer.yaml
  cluster/setup-testgrid-pubsub.sh
  cmd/api/main.go
  cmd/summarizer/main.go
  pkg/api/router.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
  pkg/api/v1/state_test.go
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  pkg/tabulator/tabstate.go
  pkg/tabulator/tabstate_test.go
Labels: lgtm, approved, size/XL

#845 Ignore poorly named objects
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_test.go
Labels: lgtm, approved, size/S

#847 Reserve a field for AutoBug use.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L

#849 Correct pubsub subscription
  cluster/canary/summarizer.yaml
Labels: lgtm, approved, size/XS

#851 Create knative tabulator
  cluster/prod/knative/tabulator.yaml
Labels: lgtm, approved, size/M

#853 Script to sync workload identity bindings
  cluster/bind-service-accounts.sh
Labels: lgtm, approved, size/L

#855 Use tab-path flag
  cluster/canary/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#859 Write tab-based summaries to summary location in canary
  cluster/canary/summarizer.yaml
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#860 Add pubsub and persistent queue for knative summarizer
  cluster/prod/knative/setup-testgrid-pubsub.sh
  cluster/prod/knative/summarizer.yaml
Labels: lgtm, approved, size/M

#861 Consume test-group pubsub subscription with tabulator
  cluster/canary/summarizer.yaml
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#862 Add tab summarizer to knative
  cluster/prod/knative/summarizer.yaml
Labels: lgtm, approved, size/M

#863 Remove canary test-group summarizer
  cluster/canary/summarizer.yaml
Labels: lgtm, approved, size/M

#865 Write tab-based summary to summary-temp in prod
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#864 Add --persist-queue support to tabulator
  cmd/tabulator/main.go
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/persist.go
  pkg/tabulator/tabstate.go
Labels: lgtm, approved, size/M

#857 Reserve new test metadata field.
  pb/config/config.pb.go
  pb/config/config.proto
  pb/state/state.pb.go
  pb/state/state.proto
Labels: lgtm, approved, size/XL

#866 Use tab-based summaries in production
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#873 Persist the canary tabulator queue
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#868 Add option to override build ID with config value.
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
Labels: lgtm, approved, size/XL

#872 Move the test-group-updates subscription over to the tabulator.
  cluster/prod/knative/summarizer.yaml
  cluster/prod/knative/tabulator.yaml
  cluster/prod/summarizer.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/S

#874 Persist production tabulator queues
  cluster/prod/knative/tabulator.yaml
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS

#875 Delete unused summarizers
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/M

#878 Migrate api to read from tab state
  cluster/canary/api.yaml
Labels: lgtm, approved, size/XS

#880 Add newline at end of file.
  cluster/create-subscription.sh
Labels: lgtm, approved, size/XS

#881 Wrap copy source errors as storage.ErrObjectNotExist
  util/gcs/BUILD.bazel
  util/gcs/real_gcs.go
  util/gcs/real_gcs_test.go
Labels: lgtm, approved, size/L
