Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-12, with the labels that each got.

#1086 Normalize API input for resource names
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_http_test.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server_fake.go
  pkg/api/v1/state.go
  pkg/api/v1/state_test.go
Labels: lgtm, approved, size/XXL

#1092 Cache default config as map in API component
  config/cache.go
  config/config.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_cache.go
  pkg/api/v1/config_cache_test.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
Labels: lgtm, approved, size/XL

#1095 set ACCEPTABLE as a separate tab status
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1097 fix golint issues
  pkg/api/v1/config.go
  pkg/api/v1/config_test.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
Labels: lgtm, approved, size/L, ok-to-test

#1102 Re-update the singleton_autobug documentation.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/XS
