Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-02, with the labels that each got.

#792 Initialize summarizer queue
  pkg/summarizer/summary.go
Labels: lgtm, approved, size/XS

#793 Reserve field 3 of IssueState
  pb/issue_state/issue_state.pb.go
  pb/issue_state/issue_state.proto
Labels: lgtm, approved, size/XS

#791 Minor go vet changes
  config/snapshot/config_snapshot_test.go
  pkg/tabulator/tabstate.go
  pkg/updater/updater.go
Labels: lgtm, approved, size/S

#794 Support persisting test group queue across processes.
  cmd/updater/main.go
  pkg/summarizer/pubsub.go
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/persist.go
  pkg/updater/persist_test.go
  util/gcs/client.go
  util/queue.go
Labels: lgtm, approved, size/L

#796 Support test annotations.
  pb/config/config.pb.go
  pb/config/config.proto
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read.go
Labels: lgtm, approved, size/L

#798 Enable persistent queue on canary updater
  cluster/canary/updater.yaml
Labels: lgtm, approved, size/XS

#799 Enable persistent queue for prod
  cluster/canary/updater.yaml
  cluster/prod/updater.yaml
Labels: lgtm, approved, size/XS

#800 Log when there is no previous persistent queue to load.
  pkg/updater/persist.go
Labels: lgtm, approved, size/XS

#801 Remove duplicate package comment
  pkg/updater/persist.go
Labels: lgtm, approved, size/XS

#806 Improve persistent summarizer queue
  pkg/summarizer/persist.go
  pkg/summarizer/summary.go
  util/queue/persist.go
Labels: lgtm, approved, size/S

#804 Refactor config snapshot to use channels
  config/snapshot/BUILD.bazel
  config/snapshot/config_snapshot.go
  config/snapshot/config_snapshot_test.go
  pkg/summarizer/summary.go
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
Labels: lgtm, approved, size/XL

#809 Use persistent queue on knative updater
  cluster/prod/knative/updater.yaml
Labels: lgtm, approved, size/XS

#805 Persist summarizer queue
  cluster/canary/summarizer.yaml
Labels: lgtm, approved, size/XS

#810 Implement custom evaluator rules for junit results
  pb/custom_evaluator/custom_evaluator.pb.go
  pb/custom_evaluator/custom_evaluator.proto
  pkg/updater/BUILD.bazel
  pkg/updater/eval.go
  pkg/updater/eval_test.go
  pkg/updater/gcs.go
  pkg/updater/read.go
Labels: lgtm, approved, size/XL

#814 Set conditions for client
  config/snapshot/config_snapshot.go
Labels: lgtm, approved, size/M

#817 Improve persistent queue routine.
  util/queue/persist.go
Labels: lgtm, approved, size/M

#819 Improve some godoc
  pkg/updater/eval.go
  util/queue/queue.go
Labels: lgtm, approved, size/XS

#816 Enable persistent summarizer queue in prod
  cluster/prod/knative/summarizer.yaml
  cluster/prod/summarizer.yaml
Labels: lgtm, approved, size/XS

#820 Remove tabs in .kazelcfg.json
  .kazelcfg.json
Labels: lgtm, approved, size/XS

#822 Add Tabulator to canary.
  cmd/tabulator/BUILD.bazel
  images/BUILD.bazel
Labels: lgtm, approved, size/XS

#825 Config snapshot adjustments
  config/snapshot/config_snapshot_test.go
  pkg/summarizer/summary.go
  pkg/updater/BUILD.bazel
  pkg/updater/updater.go
Labels: lgtm, approved, size/L

#828 Use a specific image for canary Tabulator.
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#830 Differentiate between file-does-not-exist and other errors.
  pkg/tabulator/BUILD.bazel
  pkg/tabulator/tabstate.go
  util/gcs/local_gcs.go
Labels: lgtm, approved, size/S

#832 Fix JUnit struct definitions to follow https://llg.cubic.org/docs/junit/
  go.sum
  metadata/junit/junit.go
  metadata/junit/junit_test.go
  pkg/updater/eval.go
  pkg/updater/gcs.go
  pkg/updater/gcs_test.go
  pkg/updater/read_test.go
Labels: lgtm, approved, size/L

#833 Add Tabulator to prod.
  cluster/prod/BUILD.bazel
  cluster/prod/tabulator.yaml
  util/gcs/local_gcs.go
Labels: lgtm, approved, size/M
