Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-11, with the labels that each got.

#1070 Added a feature to ignore cols & enforce min # of runs
  cmd/summarizer/main.go
  go.mod
  internal/result/BUILD.bazel
  internal/result/results.go
  internal/result/results_test.go
  pb/config/config.pb.go
  pb/config/config.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/XXL, ok-to-test

#1072 Include unspecified value in enum (config.proto)
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/L, needs-ok-to-test

#1073 API improvements
  cmd/api/main.go
  pkg/api/router.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_http_test.go
  pkg/api/v1/json.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
  pkg/api/v1/state_http_test.go
Labels: lgtm, approved, size/L

#1074 Update singleton_autobug documentation.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/XS

#1077 Add string-not-equal operation in eval.
  pkg/updater/eval.go
  pkg/updater/eval_test.go
Labels: lgtm, approved, size/M

#1076 Add an explicit package for config.proto.
  pb/api/v1/data.pb.go
  pb/api/v1/data.proto
  pb/config/config.pb.go
  pb/config/config.proto
  pb/state/state.pb.go
  pb/state/state.proto
  pb/updater/updater.pb.go
  pb/updater/updater.proto
Labels: lgtm, approved, size/XXL

#1080 Add an explicit package for all TestGrid protos.
  pb/BUILD.bazel
  pb/api/v1/data.pb.go
  pb/api/v1/data.proto
  pb/config/config.pb.go
  pb/config/config.proto
  pb/custom_evaluator/custom_evaluator.pb.go
  pb/custom_evaluator/custom_evaluator.proto
  pb/issue_state/issue_state.pb.go
  pb/issue_state/issue_state.proto
  pb/state/state.pb.go
  pb/state/state.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pb/test_status/test_status.pb.go
  pb/test_status/test_status.proto
  pb/updater/BUILD.bazel
  pb/updater/updater.pb.go
  pb/updater/updater.proto
Labels: lgtm, approved, size/XXL

#1081 Add issue source to config.proto.
  pb/config/config.pb.go
  pb/config/config.proto
Labels: lgtm, approved, size/XXL

#1083 Refactor API to get config snapshot
  config/snapshot/config_snapshot.go
  config/snapshot/config_snapshot_test.go
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/config.go
  pkg/api/v1/config_http_test.go
  pkg/api/v1/server.go
  pkg/api/v1/state.go
  pkg/api/v1/state_http_test.go
Labels: lgtm, approved, size/L

#1085 Fix string comparison for custom statuses.
  pkg/updater/eval.go
  pkg/updater/eval_test.go
Labels: lgtm, approved, size/M

#1090 Throtle concurrency of tabulator to match updater in canary
  cluster/canary/tabulator.yaml
Labels: lgtm, approved, size/XS

#1091 Throttle tabulator to 10 concurrent states
  cluster/prod/tabulator.yaml
Labels: lgtm, approved, size/XS
