Repository GoogleCloudPlatform/testgrid, pull requests merged in 2022-10, with the labels that each got.

#1061 Added a feature to categorize tab as acceptably flaky.
  cmd/summarizer/main.go
  config/config.go
  config/config_test.go
  pb/config/config.pb.go
  pb/config/config.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
Labels: lgtm, approved, size/XXL, ok-to-test

#1064 Fixed the golint issue with variable naming
  config/config.go
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1067 Add gRPC support to API
  cmd/api/README.md
  cmd/api/main.go
  pkg/api/BUILD.bazel
  pkg/api/router.go
Labels: lgtm, approved, size/L
