Repository GoogleCloudPlatform/testgrid, pull requests merged in 2023-04, with the labels that each got.

#1177 Fix the terser plugin import.
  web/rollup.config.js
Labels: lgtm, approved, size/XS

#1179 Add Dashboards, Dashboard-Groups and onclick functionality to render respective Dashboard-groups
  web/custom-elements.json
  web/src/APIClient.ts
  web/src/TestgridIndex.ts
  web/src/dashboard-summary.ts
  web/stories/testgrid-index.stories.ts
  web/test/testgrid-index.test.ts
Labels: lgtm, approved, size/XL, needs-ok-to-test

#1180 Add npm presubmit job.
  .prow.yaml
  web/package-lock.json
  web/package.json
Labels: lgtm, approved, size/XL

#1181 MVP for routing
  web/custom-elements.json
  web/index.html
  web/package-lock.json
  web/package.json
  web/src/testgrid-app.ts
  web/src/testgrid-index.ts
  web/src/testgrid-router.ts
  web/src/utils/navigation.ts
  web/stories/testgrid-index.stories.ts
  web/test/testgrid-index.test.ts
  web/web-dev-server.config.mjs
Labels: lgtm, approved, size/XXL

#1183 Improve the tests
  web/src/testgrid-index.ts
  web/src/testgrid-router.ts
  web/test/testgrid-index.test.ts
  web/web-test-runner.config.mjs
Labels: lgtm, approved, size/L

#1184 Render content when the page is loaded
  web/package-lock.json
  web/src/dashboard-summary.ts
  web/src/testgrid-index.ts
  web/src/testgrid-router.ts
  web/src/utils/navigation.ts
  web/test/dashboard-summary.test.ts
  web/test/testgrid-index.test.ts
Labels: lgtm, approved, size/L

#1186 Fix to show storybook stories instead of app index.
  web/.storybook/server.mjs
  web/custom-elements.json
  web/package.json
Labels: lgtm, approved, size/XXL

#1185 Add the tab bar with tab names
  web/custom-elements.json
  web/package-lock.json
  web/package.json
  web/src/dashboard-summary.ts
  web/test/dashboard-summary.test.ts
Labels: lgtm, approved, size/L

#1189 Add a tab bar with proper navigation and grid data placeholder.
  web/custom-elements.json
  web/src/tab-summary.ts
  web/src/testgrid-app.ts
  web/src/testgrid-dashboard-summary.ts
  web/src/testgrid-data-content.ts
  web/src/testgrid-grid-display.ts
  web/src/testgrid-index.ts
  web/src/testgrid-router.ts
  web/src/utils/constants.ts
  web/src/utils/navigation.ts
  web/stories/tab-summary.stories.ts
  web/test/dashboard-summary.test.ts
  web/test/testgrid-dashboard-summary.test.ts
  web/test/testgrid-data-content.test.ts
  web/test/testgrid-grid-display.test.ts
  web/test/testgrid-index.test.ts
Labels: lgtm, approved, size/XXL
