Repository GoogleCloudPlatform/testgrid, pull requests merged in 2023-11, with the labels that each got.

#1254 Insert icon and message to inflated column cell
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1266 Fix lint issues from code import
  pkg/updater/resultstore/client.go
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
  resultstore/resultstore.go
  resultstore/resultstore_test.go
Labels: lgtm, approved, size/L

#1264 Add links for alerts, and utilities to process link templates.
  pkg/summarizer/BUILD.bazel
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  util/BUILD.bazel
  util/links.go
  util/links_test.go
Labels: lgtm, approved, size/XL

#1267 Add cell metrics to resultstore
  pkg/updater/gcs.go
  pkg/updater/resultstore/BUILD.bazel
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/L
