Repository GoogleCloudPlatform/testgrid, pull requests merged in 2023-08, with the labels that each got.

#1245 Bump Go dependencies
  go.mod
  go.sum
  repos.bzl
Labels: lgtm, approved, size/XXL

#1242 Extract grouping ID based on configurations
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/M, ok-to-test

#1246 Group invocations according to grouping strategy
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/L

#1247 Process groups instead of individual invocations
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/L

#1248 Enable custom target result status
  pkg/updater/resultstore/BUILD.bazel
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/L

#1251 add functionality to extract custom headers
  pkg/updater/resultstore/resultstore.go
  pkg/updater/resultstore/resultstore_test.go
Labels: lgtm, approved, size/L
