Repository GoogleCloudPlatform/testgrid, pull requests merged in 2024-02, with the labels that each got.

#1271 Add custom column headers to summarizer
  pb/state/state.pb.go
  pb/state/state.proto
  pb/summary/summary.pb.go
  pb/summary/summary.proto
  pkg/summarizer/summary.go
  pkg/summarizer/summary_test.go
  pkg/tabulator/tabstate.go
  pkg/updater/updater.go
  pkg/updater/updater_test.go
  util/links_test.go
Labels: lgtm, approved, size/XL, ok-to-test

#1269 Add config validation for result sources.
  config/config.go
  config/config_test.go
Labels: lgtm, approved, size/L

#1272 Clarify message for missing podinfo.json.
  util/gcs/read.go
Labels: lgtm, approved, size/XS

#1273 Fixing a panic when recording column headers in alerts.
  pkg/updater/updater.go
  pkg/updater/updater_test.go
Labels: lgtm, approved, size/S
